-- FUNCIONES EN COMANDOS SQL , EL PODER DE LAS FUNCIONES, NO OCUPO CURSORES PARA RECORRER
-- SOLO PARAMETROS DE TIPO IN 
-- DEBE ESTAR EN DATABASE
-- DEVOLVER TIPO DE DATO SQL O PL-SQL

SELECT FIRST_NAME, SALARY, CALC_TAX_F(EMPLOYEES.employee_id,18) AS Descuento FROM EMPLOYEES;